name: Badges

on: [push]

jobs:
  update_badges:
    name: Update Badges
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Download cloc
        run: |
          sudo apt-get update -y
          sudo apt-get install -y cloc
      - name: Create Badges
        run: |
          LOC="$(./cloc.sh --loc)"
          PERCENTAGE="$(./cloc.sh --percentage)"

          LOC_BADGE="$(wget -qO- https://img.shields.io/badge/Lines_of_Code-$LOC-lightgrey.svg | sed 's/\"/\\"/g')"
          PERCENTAGE_BADGE="$(wget -qO- https://img.shields.io/badge/Comments-$PERCENTAGE%25-green.svg | sed 's/\"/\\"/g')"

          curl -s -X PATCH \
               -H "Content-Type: application/json" \
               -H "Authorization: token ${{ secrets.UPLOAD_BADGES }}" \
               -d '{"files": {"loc.svg": {"content": "'"$LOC_BADGE"'"}, "comments.svg": {"content": "'"$PERCENTAGE_BADGE"'"}}}' \
               https://api.github.com/gists/8f6459c2417de7534f64d98360dde865
