name: Checks

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  clang_format:
    name: Check Clang-Format
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Download Clang-Format
        run: |
          sudo apt-get update -y
          sudo apt-get install -y clang-format
      - name: Run Clang-Format
        run: ./clang-format.sh
      - name: Compare Results
        run: |
          DIFF=$(git diff)
          if [ ! -z "$DIFF" ]; then echo $DIFF && exit 1; fi

  comment_percentage:
    name: Check Comment Percentage
    runs-on: ubuntu-18.04
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v2
        with:
          path: current
          ref: ${{ github.ref }}
      - name: Checkout Base Repository
        uses: actions/checkout@v2
        with:
          path: base
          ref: ${{ github.base_ref }}
      - name: Download Cloc
        run: |
          sudo apt-get update -y
          sudo apt-get install -y cloc
      - name: Run Cloc
        run: |
          BASE="$(base/cloc.sh --percentage-only)"
          CURRENT="$(current/cloc.sh --percentage-only)"
          echo "Percentage of Comments in Base Repository: $BASE"
          echo "Percentage of Comments after Merge: $CURRENT"
          if (( $(echo "$BASE > $CURRENT" |bc -l) ))
          then
            awk -v a=$CURRENT -v b=$BASE 'BEGIN {printf "Percentage decreased! (%3.4f%)\n", (a-b)}'
            exit 1
          else
            awk -v a=$CURRENT -v b=$BASE 'BEGIN {printf "Percentage increased! (%3.4f%)\n", (a-b)}'
          fi

  shellcheck:
    name: Run ShellCheck
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run ShellCheck
        run: |
          find $GITHUB_WORKSPACE -type f -and \( -name "*.sh" \) | xargs shellcheck

  script_functionality:
    name: Check Script Functionality
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Check error conditions # Currently, gettext is not installed. Both if statements should be false.
      run: |
        if $GITHUB_WORKSPACE/compile-locales.sh; then
          if $GITHUB_WORKSPACE/update-locales.sh; then
            exit 1
          fi
        fi
    - name: Check correct workflow # Now, gettext will be installed and both INVERTED if statements should be false.
      run: |
        sudo apt-get update -qq && sudo apt-get install gettext -qq -y
        if ! $GITHUB_WORKSPACE/compile-locales.sh; then
          if ! $GITHUB_WORKSPACE/update-locales.sh; then
            exit 1
          fi
        fi
