name: Deploy

on:
  push:
    tags:
      - '**'

jobs:
  source_code:
    name: Extension Bundle
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Checkout Submodules
      run: git submodule update --init
    - name: Create Release
      run: |
        mkdir swingpie@schneegans.github.com
        mv client common presets schemas server settings swingpie@schneegans.github.com
        mv *.js README.md LICENSE swingpie@schneegans.github.com
        zip -r swingpie@schneegans.github.com.zip swingpie@schneegans.github.com
    - name: Upload Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: swingpie@schneegans.github.com.zip
        asset_name: swingpie@schneegans.github.com.zip
        tag: ${{ github.ref }}
        overwrite: true
