name: Deploy

on:
  push:
    tags:
      - '**'

jobs:
  source_code:
    name: Extension Bundle
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Checkout Submodules
      run: git submodule update --init
    - name: Create Release
      run: |
        mkdir flypie@schneegans.github.com
        mv common daemon presets resources schemas settings flypie@schneegans.github.com
        mv *.js metadata.json README.md LICENSE flypie@schneegans.github.com
        zip -r flypie@schneegans.github.com.zip flypie@schneegans.github.com
    - name: Upload Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: flypie@schneegans.github.com.zip
        asset_name: flypie@schneegans.github.com.zip
        tag: ${{ github.ref }}
        overwrite: true
